### ISSUE TITLE
LaTeX-to-Unicode inserts tab after unicode symbol for some symbols

### ISSUE THREAD

**Issue by Kelet** [JuliaLang/julia-vim#28]
\alpha\<Tab> = `α<Tab symbol>`
\ne\<Tab> = `≠`

GVim 7.4, Windows, commit e35c2482fc2e4e0ccd33858ff4cea77ce4c7bcde

**Comment by carlobaldassi** [comment]
I still don't know what is the origin of the issue, but at least some of it should have improved with the last commit. It'd be helpful if someone who is experiencing this issue could confirm.

**Comment by carlobaldassi** [comment]
I finally managed to test things on Windows and was able to reproduce the bug. It should be solved now. Otherwise please comment and I'll reopen the issue.
