### ISSUE TITLE
Use LaTeX-to-Unicode for other file types

### ISSUE THREAD

**Issue by jovaha** [JuliaLang/julia-vim#33]
The LaTeX-to-Unicode is a very useful feature in general text editing, so it would be nice to be able to use it for any file type. Is this possible?

**Comment by mbaz** [comment]
How do you specify just some file types? I'd like to have this functionality only for Julia and Latex files. I have tried combinations such as `"julia, tex"`, `"julia tex"`, `"*jl *tex"`, but they don't work.

**Comment by carlobaldassi** [comment]
@mbaz Like this:

```
let g:latex_to_unicode_file_types = ["julia", "tex", "plaintex"]
```

see also [the help](https://github.com/JuliaLang/julia-vim/blob/e33061769718e3af128ccb5c97427cc863f888d5/doc/julia-vim.txt#L175) (or better `:help julia-vim-L2U-file-types`).

**Comment by mbaz** [comment]
@carlobaldassi Thanks! and sorry for missing the documentation. I went by the project's readme, which only has `".*"` as an example, and I didn't know how to specify a list.
