### ISSUE TITLE
Undo filetype=lisp not working on OS X MacVim

### ISSUE THREAD

**Issue by jfsantos** [JuliaLang/julia-vim#38]
Even though I am using MacVim (Vim 7.4), there is still an issue with my .jl files always being detected as LISP. I tried removing the `if v:version < 704` line to force the `undo_ftplugin`command but it did not work.   I do not have any other LISP plugins installed but I am using a quite involved configuration. However, none of my plugins define anything for .jl files, so I do not believe this is the source of this issue.

What extra info can I send you to help solve this issue?

**Comment by byronyi** [comment]
@carlobaldassi Yes it does work.

**Comment by carlobaldassi** [comment]
@byronyi and does adding this line at the end of `.vimrc` work?

```
autocmd BufRead,BufNewFile *.jl set filetype=julia
```

i.e. if you do that, then you quit vim, open it again with some `test.jl` file and call `:set filetype` what does it print? Still lisp?

**Comment by byronyi** [comment]
@carlobaldassi Great it works. Thank you!

**Comment by carlobaldassi** [comment]
@byronyi ok then, this means that vim is not parsing [`ftdetect/julia.vim`](https://github.com/JuliaLang/julia-vim/blob/b7e8b7a147814c7500692c28df988030d333883d/ftdetect/julia.vim) at startup (which is a problem).

Now the question is: is it reading it at all? If it isn't, then the LaTeX-to-Unicode functionality shouldn't work. If that's working, it means vim reads that file, but at a later time. Can you test this?

In any case, this seems to point to some trouble with the installation of the plugin, e.g. using a lazy plug-in manager which does not load the code right away or something like this (cfr. #35). Can you provide more details on your system and the way you used to install the plugin? Also vimrc etc.

**Comment by byronyi** [comment]
@carlobaldassi No it seems not working. When I type ``\alpha``, what I see is still ``\alpha``, not ``α``.

I have been using the plugin installed by Vundle. My system is OS X 10.10, with Vim version as follows:
```
$ vim --version
+dialog_con_gui  -lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
+farsi           +mouse_netterm   +syntax
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -L/usr/local/lib -L. -L/usr/local/lib -L/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -framework CoreFoundation -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.10 -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -framework Python   -framework Ruby
```

**Comment by carlobaldassi** [comment]
@byronyi In your `vimrc` file, you need to move the line `filetype plugin indent on` to the bottom, after you load the `julia-vim` plugin.
It also seems you should put a `set nocompatible` in there somewhere, probably at the top.
(Remove the `autocmd` line of course.)

**Comment by carlobaldassi** [comment]
Oh and you also need to put a line `call vundle#end()` right after the last `Plugin` line, before the `filetype plugin indent on` line.

**Comment by byronyi** [comment]
Great it works. I guess that's because last update of my vimrc is just long time ago.

Thanks a lot!

**Comment by carlobaldassi** [comment]
This issue seems to be likely due to incorrect plugin installation. I'll close it. @jfsantos, @brk00 please comment here if you still have problems.
