### ISSUE TITLE
Syntax folding trouble

### ISSUE THREAD

**Issue by akxlr** [JuliaLang/julia-vim#41]
Hi, I am having trouble with `foldmethod=syntax` on the following (example) file:

    function f()
        a, b = {x for x in {1, 2}}
    end

    function g()
        println("hello")
    end

Hitting `za` with the cursor on the first line folds the entire file, when it should only fold the top function.

Is there something wrong with my vim config or is this a bug?

**Comment by carlobaldassi** [comment]
Actually looks like a vim bug to me, but it should be fixed nonetheless now. Thanks for the report.
