### ISSUE TITLE
NERDTree and completion

### ISSUE THREAD

**Issue by robertdj** [JuliaLang/julia-vim#44]
Hi,

I am experiencing an odd problem: After opening files with NERDTree word completion does not work. If I don’t use NERDTree word completion works just fine.

Any ideas why this happens?

Thanks,

Robert

**Comment by carlobaldassi** [comment]
Could you be more specific in the description of the problem? What kind of completion doesn't work? Vim's built-in, LaTeX, some other plugin's? What vim version are you using, from which OS? Anything particular in your vimrc file?

**Comment by robertdj** [comment]
Sorry about the lack of details. 
I'm using Vim 7.4.* on Mac Yosemite and Linux Mint 17. 
I thought there was only one kind of word completion? In a bare Vim it is the completion you get when pressing CTRL-n in the middle of a word. Currently I am using TAB in the form of the Supertab plugin or a function that is seen in my vimrc:
https://github.com/robertdj/dotfiles/blob/master/vimrc

**Comment by carlobaldassi** [comment]
@robertdj this should be fixed now, thanks for the inputs. If not, please comment and I'll reopen.

**Comment by robertdj** [comment]
It certainly seems to work now :-) Thanks a lot!
