### ISSUE TITLE
Tab and C-h interacting?

### ISSUE THREAD

**Issue by mlhetland** [JuliaLang/julia-vim#49]
Is `<Tab>` somehow using `<C-h>`? If I try to map `<C-h>` to something (specifically with `imap`), it works, but the tab key starts acting up in `julia-vim` (but nowhere else). As an example, I'll start out with a `.vimrc` with just the minimal Vundle setup for including `julia-vim`, and no other mappings or code.

Then I add the following (before the Vundle block):

```vim
imap <C-h> Hello, world!
```

Starting vim with this `.vimrc`, if I edit a non-Julia file, pressing `<Tab>` (in insert mode) will insert a tab, and pressing `<C-h>` will insert `Hello, world!`.

If I edit a Julia file, `<C-h>` also does its job, but pressing `<Tab>` will now insert:
```julia
<91>Hello, world!
```
where there is a tab character after `Hello, world!`. If I start the line with, say, `\alph` and then press tab, I get the completion:
```julia
\alpha
```
I press it again, and get:
```julia
α<91>Hello, world!
```
This time without a tab at the end.

The `<91>` is a Unicode "PRIVATE USE ONE".

It *seems* to me that this behavior is a bug, and that it is a bug in `julia-vim` – but I may very well be mistaken…

**Comment by carlobaldassi** [comment]
Thanks for the detailed report. It was an oversight: `<C-H>` is the backspace, which is what was being called.
