### ISSUE TITLE
Line endings correction

### ISSUE THREAD

**Issue by DonRyuDragoni** [JuliaLang/julia-vim#50]
I installed this plugin with pathogen, as instructed in the README.md file; however, when trying to edit a `.jl` file, this message is displayed:

```
Error detected while processing /home/ryu/.vim/bundle/julia-vim/ftdetect/julia.vim:
line    1:
E15: Invalid expression: v:version < 704^M
line   20:
E171: Missing :endif
Press ENTER or type command to continue
```

I tried converting the line endings manually with `dos2unix` (running in the `.vim/bundle` directory):

```shell
for file in $(find .); do dos2unix $file; done
```

And now everything works fine in my Ubuntu 14.10.

As far as I know, this is only related to the line endings of the files; so, could you add this command to the installation instructions or correct the line endings?

Thanks in advance.

**Comment by carlobaldassi** [comment]
This is strange, the original files don't have dos line endings. I did a fresh git clone and made sure I don't get dos line endings either.
You can even download the [raw file](https://raw.githubusercontent.com/JuliaLang/julia-vim/master/ftdetect/julia.vim) and verify that it uses just `\n` as line ending, there's no `\r` there.
BTW I'm currently on Ubuntu 14.10 too.

Maybe there's some non-default configuration option in your git config (`cat ~/.gitconfig`)? I know there are some options about line endings (`core.eol`, `core.autocrlf` etc) but I never used them.

**Comment by DonRyuDragoni** [comment]
I rechecked the configuration file to find it was configured wrong.

Just to be safe I re-cloned the repository and everything seems fine. Sorry to bother you over nothing.
