### ISSUE TITLE
E764: Option 'omnifunc' is not set

### ISSUE THREAD

**Issue by zhmz90** [JuliaLang/julia-vim#51]
There are two computers using the same .vimrc file . One is normal, while the other one can't use tab only within a julia file. When I input tab, the error is : E764: Option 'omnifunc' is not set. It confuses me.

my .vimrc file is at git@github.com:zhmz90/myvimrc.git

Thanks,

Lanting

**Comment by ninjin** [comment]
I am suffering from the same issue using vim 7.4.273 and 7.4.729.

**Comment by carlobaldassi** [comment]
I tried @zhmz90's vimrc file on a clean install (fresh .vim directory) and I could not reproduce the issue. My version of vim is 7.4.273, so it's one of those mentioned by @ninjin.
I'm confused as well. I tried googling the error but with no luck as to what may be wrong.

@zhmz90 can you spot any difference in the two machines? E.g. the operating system, and the output of `vim --version` (or of `:version` from within vim).

**Comment by zhmz90** [comment]
@carlobaldassi  Thank you very much!  
the normal OS and vim is at : 
https://github.com/zhmz90/myvimrc/blob/master/normal.txt
The bad OS and vim version information is at : 
https://github.com/zhmz90/myvimrc/blob/master/bad.txt 

All the files are at my repository https://github.com/zhmz90/myvimrc.git

**Comment by carlobaldassi** [comment]
Well, they're identical! I'm still more confused.

But I found a small typo in the plugin code. I don't see why it would matter, but can you try to update the plugin and see if the error magically goes away?

If not, here's one more quick test: try running `vim -i /dev/null somefile.jl` on the bad computer. That avoids loading the `~/.viminfo` file, which is the other thing which may be different besides vimrc (even if I still don't know why it would matter).

**Comment by ninjin** [comment]
Here is a minimal `.vimrc` that exhibits the behaviour:

    set nocompatible
    filetype plugin on

I can replicate the issue on 7.4.273 with only julia-vim installed and the above `.vimrc`.

**Comment by carlobaldassi** [comment]
@ninjin: how did you install julia-vim? That does not look like a .vimrc which would use a plugin manager like vundle.

**Comment by ninjin** [comment]
@carlobaldassi: I removed the symlinks that I usually have for `.vim` and `.vimrc`, then I simply ran `git clone git@github.com:JuliaLang/julia-vim.git ~/.vim` and put the minimal `.vimrc` in place.  Not all that sophisticated, but it got the debugging done.

**Comment by carlobaldassi** [comment]
I see. I tried that, and still can not reproduce the issue, everything works for me.
Did you try not loading the viminfo file I assume?

**Comment by ninjin** [comment]
Well, I did `rm -f ~/.viminfo`, I hope that would do the trick.  I am currently using julia-vim as usual again, after removing the `plugin` argument from `filetype` in my `.vimrc`.  Sorry not to be much help, vim scripting is not something that I am particularly good at.

**Comment by carlobaldassi** [comment]
You've been as helpful as possible, I really have no idea how the exact same configuration can produce different results. There must obviously be something different, but I don't know what it may be.
Does it work if you give this command while editing a julia file:

```
:set omnifunc=LaTeXtoUnicode#omnifunc
```

?

(note: you need to update the plugin to the latest version.)

**Comment by ninjin** [comment]
Yes, that resolves it!

**Comment by newptcai** [comment]
Hmm, I also have exactly the same problem. Only happens on one machine.
