### ISSUE TITLE
[Feature request] Hanging indent for long lines

### ISSUE THREAD

**Issue by bkkrueger** [JuliaLang/julia-vim#52]
When I have a long line, julia-vim does not use a hanging indent for the second (and later) line(s).  If I put them in manually, I then have to manually undo the extra indent for the next line of code.  As it's not uncommon for me to have a long line (for example, complex mathematical expressions where the variables in the expression are more than a few characters long), I run into this regularly.  If I have a block of code and there is a long line in the middle, it makes it difficult to read because it's not clear which lines are continuations of previous lines.  Adding a hanging indent for long lines would be very helpful.

**Comment by carlobaldassi** [comment]
I have this issue too. Can you be more precise about what behaviour you would like to have, or do you have an example of a language plugin which does what you want, or both?

**Comment by bkkrueger** [comment]
What I would like is for a long line (I generally consider anything 80 characters or longer to be a "long line") to continue on a new line.  I would like the continuation line(s) to have a hanging indent automatically.  When I go on to a new line, I would like it to return to the correct indentation.  For example:

```
    this_is_a_really_long_line = with_very_long_variable_names * to_test /
        the_hanging_indent_feature
    this_is_the_next_line
```

I'm not sure of a perfect example.  The C++11 vim scripts that I have don't automatically break long lines, but if I put in the line breaks myself they will have the appropriate hanging indent.  I believe I got the vim scripts for C++11 from here: https://github.com/vim-scripts/Cpp11-Syntax-Support

**Comment by carlobaldassi** [comment]
The problem with julia compared to C/C++ is that the syntax is more permissive, so it's really hard to detect when a line of code is not terminated (without having a full blown julia parser in vim). One obvious case would be when some open bracket is not closed, but that's far from covering all possibilities.
I'll have a look and see what's feasible.

**Comment by axsk** [comment]
I have to say that, while I think having hanging indents on *all* long lines would be nice, it mainly annoys me when I have to indent manually in an open `(` block.

Would *really* like this fixed, but my vimfoo is not strong enough :(

**Comment by carlobaldassi** [comment]
I fixed the case of parentheses/brackets, this is how things are indented now:

```julia
function test(a::Int,
              b::Float64,
              c::Int)
    a + b + c
end
```

The general case is not really doable, so I'm closing this.
