### ISSUE TITLE
<unique> mapping conflicts with existing mapping

### ISSUE THREAD

**Issue by zyedidia** [JuliaLang/julia-vim#53]
Line 252 in `autoload/julia_blocks.vim` is causing an error in the startup of Neovim:
```vimL
vnoremap <buffer><silent><unique> <Esc> <Esc>:call julia_blocks#select_reset()<CR>
```
This can be fixed by removing the `<unique>` part of the mapping, but I am not sure if that is safe to do.

The error is:

```
Error detected while processing function julia_blocks#init_mappings:
line    22:
E225: global mapping already exists for ^[
```

**Comment by carlobaldassi** [comment]
That `<unique>` is a rudimentary fail-safe mechanism to avoid overwriting other user-defined methods. It's a very poor solution, an the error is annoying, but at least it avoids more subtle problems. I'd like to improve it but I'm not sure what's the best way.

In any case: what the error means is that you already have a mapping of `<Esc>` in visual mode to something else. I don't think it's related to Neovim, it's more likely that you have it defined in your `.vimrc` or by some other plug-in.
You should be able to see that by looking at the output of this command on a non-julia file:

```
:verbose vmap <Esc>
```

After that, you can decide what's better for your case:

1. overwrite your mapping with the one provided by julia-vim, by removing the `<unique>` (unlikely)
2. avoid the julia-vim mapping by commenting that line.

Additional information: the purpose of the julia-vim `<Esc>` mapping is to reset the julia_blocks state when you exit the visual mode by pressing the `<Esc>` key. Ideally, vim should provide an autocommand for that, like it does for insert mode, but it doesn't, so I resorted to this crude hack. It should be fairly innocuous to remove this mapping.

**Comment by zyedidia** [comment]
I understand now. 
I thought it was Neovim causing the problem because I wasn't having the problem with vim, but when I upgraded to Neovim, the error came up. In any case, I have solved the problem on my end and will close this issue. 
Thanks for the clarification!

**Comment by carlobaldassi** [comment]
Glad to hear that.
But I think we could leave this open until a better general solution is found.

**Comment by carlobaldassi** [comment]
Oh and by the way did you have a conflicting plug-in installed?

**Comment by zyedidia** [comment]
No, it was something in my `.vimrc`.
