### ISSUE TITLE
Searching for unicode symbol

### ISSUE THREAD

**Issue by dpo** [JuliaLang/julia-vim#55]
I very much like the LaTeX-to-Unicode feature of `julia-vim`, but how can I search my source code for a unicode symbol? I'm using terminal-vim on OSX. Hitting `:/\alpha` and pressing the space bar doesn't complete the `\alpha` in the search bar.

Thanks!

**Comment by carlobaldassi** [comment]
you need to use shift-tab. this is also true for commands. unfortunately I haven't found a better solution.

**Comment by dpo** [comment]
Not sure I understand:

![screen shot 2015-09-15 at 11 25 10](https://cloud.githubusercontent.com/assets/38760/9881132/94c2b99c-5b9c-11e5-9417-cecfc59d2688.PNG)
![screen shot 2015-09-15 at 11 25 26](https://cloud.githubusercontent.com/assets/38760/9881144/9e8de212-5b9c-11e5-8978-0c5302c881ae.PNG)

What am I doing wrong?

**Comment by carlobaldassi** [comment]
Does pressing `<Tab>` work in insert mode during file editing?
It should be controlled by the option `g:latex_to_unicode_tab` (see [docs](https://github.com/JuliaLang/julia-vim/blob/619765de7e9862fb5a5882c5eea36aeab5c0643b/doc/julia-vim-L2U.txt#L214)) and affects the `<S-Tab>` command-line substitution as well.
Maybe you disabled it?

**Comment by dpo** [comment]
You're right. I disabled it because it conflicts with YouCompleteMe. But because YCM conflicts with so many other packages I use, I discarded it, restored `g:latex_to_unicode_tab`, and now the shift-TAB technique works for searching. Thanks much!
