### ISSUE TITLE
LaTeX-to-Unicode with Python

### ISSUE THREAD

**Issue by bkkrueger** [JuliaLang/julia-vim#57]
I love the LaTeX-to-Unicode feature in Julia, and would also like to use it in Python3.  Following the Julia-vim documentation, I included the line
      let g:latex_to_unicode_file_types = ".*"
in my .vimrc file.  If I open a .txt file, the LaTeX-to-Unicode feature works fine.  However, in a .py file when I hit tab I get the error message
      -- Omni completion (^O^N^P) Pattern not found
If I call LaTeXtoUnicode#Enable(), nothing changes.  But if I call LaTeXtoUnicode#Toggle() twice, then the LaTeX-to-Unicode feature turns off then back on and starts to work.  I tried various ways of calling LaTeXtoUnicode#Toggle() twice in my vim initialization (I'm not really a vim expert though), and didn't have any luck.  Is there a way to enable the LaTeX-to-Unicode feature in Python3 without having to manually call the toggle function twice after starting up vim?

**Comment by carlobaldassi** [comment]
This "double toggle" thing has occasionally happened to me as well (even in the middle of editing a file, while it was working), and it baffles me. As a very crude way to quickly fix the issue I mapped a key to toggle the feature, and when it happens I just use it twice:

```viml
"LaTeX-to-Unicode
noremap <expr> <F7> LaTeXtoUnicode#Toggle()
inoremap <expr> <F7> LaTeXtoUnicode#Toggle()
```

I'd love to find out what is going wrong though. I'll try to investigate a little harder.

**Comment by carlobaldassi** [comment]
I found the problem with python files and fixed it. Note however that this means that python's omnicompletion (triggered by `^X^O`) will not work when LaTeX-to-Unicode is active (but it will be restored if you deactivate it).

If you want to use both, you need to either toggle L2U, or rely on the [substitute-as-you-type setting](https://github.com/JuliaLang/julia-vim/blob/8a869d96e61fe095b2cc842db02f249e405db088/doc/julia-vim-L2U.txt#L140).

**Comment by bkkrueger** [comment]
Works great now.  Thank you!
