### ISSUE TITLE
matchit and julia-vim causes sporadic behaviour with mouse

### ISSUE THREAD

**Issue by danielarndt** [JuliaLang/julia-vim#60]
I've been using julia-vim for quite a while with no problems, but recently enabled matchit so I could do some more efficient browsing.

```runtime macros/matchit.vim```

I have mouse support enabled in vim. After enabling matchit, my mouse causes all sorts of problems. After a few click-and-drags, the mouse starts randomly inserting characters and preforming commands. It seems like the mouse is inputting directly to the editor.

* The behaviour goes away as soon as I disable matchit
* matchit itself seems to work correctly. That is, browsing using commands such as ```[[``` works as expected.
* The mouse does not cause problems in other file types with matchit enabled, leading me to believe this is a ```julia-vim``` issue.

**Comment by carlobaldassi** [comment]
Thanks for the detailed report. This is puzzling, I'm using matchit and the mouse myself, with no problems, and I don't see how they would interact.
I'll try to investigate. In the meanwhile, can you provide some additional detail, e.g. operating system, vim version, if using vim in a terminal or vim-gnome etc.?

**Comment by carlobaldassi** [comment]
Can you try commenting [this line](https://github.com/JuliaLang/julia-vim/blob/8a869d96e61fe095b2cc842db02f249e405db088/autoload/julia_blocks.vim#L252) and see if the problems persist?

**Comment by danielarndt** [comment]
Sure. I didn't know how much detail to give since I didn't know if it was as simple as matchit + julia-vim ... 

* OS: Ubuntu 14.04
* VIM: Vi IMproved 7.4
* Use case: Running vim from command-line in a tmux pane, in gnome-terminal locally

**Comment by danielarndt** [comment]
https://github.com/JuliaLang/julia-vim/issues/60#issuecomment-148083070

That seems to have fixed it. At what cost?

**Comment by carlobaldassi** [comment]
> That seems to have fixed it. At what cost?

Good to know, thanks. That line tries to make the behaviour of the julia-blocks related functionality consistent, such that when selecting a block (`vaj`), then exiting Visual mode, then selecting a block again, the selection procedure will start from scratch.
So the cost is not terrible, just annoying.
I'll need to figure out a way to do this by other means, if possible (as per the comment above that line, what would really be needed is an autocommand associated to the "exit from visual mode" event, which is currently unavailable in Vim).

**Comment by danielarndt** [comment]
Thanks. 

Let me know if you need anything else tested, or further details to reproduce.
