### ISSUE TITLE
neovim Latex-to-Unicode Support

### ISSUE THREAD

**Issue by xanderdunn** [JuliaLang/julia-vim#62]
I have `let g:latex_to_unicode_auto = 1` in my ~/.config/nvim/init.vim.

In a julia file, when I type `\neq `, nothing happens.  

When I type `\alpha `, I get:
<img width="107" alt="screen shot 2015-11-22 at 20 41 17" src="https://cloud.githubusercontent.com/assets/1313618/11330049/68261f9e-9159-11e5-8cad-dab161309c76.png">

So, it sort of worked.  The unicode alpha symbol was inserted, but the `alpha` characters remain and it looks like some unusual character (escape?) sequence `<91>` was inserted.

Many thanks for this plugin!

**Comment by xanderdunn** [comment]
@carlobaldassi It looks like the bit about `neq` can be ignored.  [It's defined](https://github.com/JuliaLang/julia-vim/blob/master/autoload/julia_latex_symbols.vim#L588) as `neqsim`, which works the same as all the other defined symbols: 
<img width="155" alt="screen shot 2015-11-29 at 16 05 06" src="https://cloud.githubusercontent.com/assets/1313618/11461184/fbc245ee-96b2-11e5-837a-41d16f46b5a9.png">

So, the issue is simply that it looks like [the escape sequence to get out of completion mode](https://github.com/JuliaLang/julia-vim/blob/master/autoload/LaTeXtoUnicode.vim#L80) isn't working in neovim, hence the `<91>`.

**Comment by carlobaldassi** [comment]
Thanks for the report, I'll have to try out neovim and see what can be done.

**Comment by carlobaldassi** [comment]
I just installed neovim and I can't reproduce the problem, everything works in my setup.
Could you provide more details about your system? In particular, the OS, the neovim version (I just cloned the most recent from github) and possibly a minimal `nvim/init.vim` for which you see the problem.

Did you maybe try this with vim as well?

**Comment by xanderdunn** [comment]
@carlobaldassi Thanks for looking at this.  I've also installed neovim from HEAD on GitHub.  It's version: 
```
NVIM 0.1.0-dev (compiled Nov 29 2015 21:04:24)
Commit: 7d42e9b7e8169da45e32c415babc27b197a26f8a
```

After doing a binary search commenting out lines in my init.vim, I discovered it was specifically this line and no more or less that caused it: 
`"inoremap <silent> <c-h> <Esc>:TmuxNavigateLeft<cr>I`

Wow!  These are commands I use to navigate between tmux panes from within vim from [this](https://github.com/christoomey/vim-tmux-navigator) plugin.  Does this make any sense to you?

**Comment by carlobaldassi** [comment]
Good catch. It doesn't make sense to me but I can reproduce this, even in vim. I'll investigate.

**Comment by carlobaldassi** [comment]
Ok I found out what happens. In vim, `<C-H>` in insert mode is the same as backspace `\b`. The auto-L2U code uses `\b` (the escape sequence inserts a character and then deletes it), and that's what triggers the problem.
I assume you don't use backspace in your workflow (if you did, it should call your tmux navigation code).
I'm not sure how to get out of this. I'll see if I can come up with some way to avoid using `\b`.

**Comment by xanderdunn** [comment]
@carlobaldassi 

Very cool, thanks.

**Comment by carlobaldassi** [comment]
Should be fixed now. I just forgot an option in the `feedkeys` call to avoid remapping.

**Comment by xanderdunn** [comment]
I updated my plugin and it works even with my Tmux key mapping.  Many thanks!
