### ISSUE TITLE
Spaces before brackets & parens; deprecated syntax

### ISSUE THREAD

**Issue by genos** [JuliaLang/julia-vim#67]
When I type in, e.g., a function definition, spaces are auto-added about which the Julia REPL complains.

For example, if I wish to type

```julia
Base.in(data, l::Leaf) = data == l.data
```

I instead get

```julia
Base.in (data, l::Leaf) = data == l.data
```

Note the space between `in` and `(`.

**Comment by genos** [comment]
This seems to be related to auto-delimiter matching; when I type `(` or `[`, a space is inserted *before* it and the matching delimiter (`)` or `]`) is inserted *after*.

**Comment by carlobaldassi** [comment]
I don't see this behaviour and wouldn't know how to explain it in relation to julia-vim. My guess is something in your configuration? Some other plugin perhaps? Otherwise, please try to provide more info (OS, vimrc...) and I'll try to track this down.

**Comment by genos** [comment]
Ah ha! Apologies, it looks like this is due to a different plugin (`vim-sexp`) firing because my setup assumes a `.jl` file deserves lisp mode.

Thanks for the responsiveness and apologies for falsely accusing your plugin!

**Comment by carlobaldassi** [comment]
The fact that `.jl` is recognized as lisp is still a bug, that's the vim default but julia-vim [should override it](https://github.com/JuliaLang/julia-vim/blob/520498d5f6e04741ab0eed7856a08e03a7ecf73d/ftdetect/julia.vim#L1-L8).

Any idea why that does not happen?

**Comment by genos** [comment]
No idea, but it does look to be the `vim-sexp` plugin that causes issues. Removing that plugin => problem disappears, reinstalling it => problem returns.

**Comment by genos** [comment]
P.S. version info:

Vim:

    $ vim -version
    VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May  5 2016 13:02:17)
    Garbage after option argument: "-version"
    More info with: "vim -h"

Mac OS X:

    $ sw_vers
    ProductName:    Mac OS X
    ProductVersion: 10.11.4
    BuildVersion:   15E65
