### ISSUE TITLE
Generator expressions not parsed correctly

### ISSUE THREAD

**Issue by tom--lee** [JuliaLang/julia-vim#71]
In the line `sum(f(i) for i in 1:n)` the ending bracket is highlighted as though it is unmatched, which is good for Julia 0.4, but in 0.5 these generator expressions are supported.

**Comment by carlobaldassi** [comment]
By default, highlighting is based on the latest stable Julia release, so 0.4 currently. Generator expressions are supported if you set the version to 0.5, see `:help julia-vim-version` ([link](https://github.com/JuliaLang/julia-vim/blob/7845b35020bb7d558fab9411decc6a367d4bd461/doc/julia-vim.txt#L55)).
