### ISSUE TITLE
Generator syntax with condition is not supported.

### ISSUE THREAD

**Issue by bicycle1885** [JuliaLang/julia-vim#76]
Even if I set the julia version to 0.5, the generator syntax with condition is not properly highlighted.

```
let g:default_julia_version = "0.5"
```

<img width="523" alt="screen shot 2016-09-11 at 16 40 48" src="https://cloud.githubusercontent.com/assets/905683/18415924/94e69712-783e-11e6-8c00-5f1a85d93983.png">

I'm using the latest commit (6debbd1ecd2b2654040bb7945412c4a39d0377a7) on NeoVim 0.1.5.

**Comment by carlobaldassi** [comment]
Thanks for pointing this out.

**Comment by bicycle1885** [comment]
It works perfectly. Thanks a lot!
