### ISSUE TITLE
Generator expressions with filtering in v0.5 break highlighting

### ISSUE THREAD

**Issue by helgee** [JuliaLang/julia-vim#79]
e.g.
```julia
[e for e in x if e > 0]
```

**Comment by helgee** [comment]
![bildschirmfoto 2016-09-13 um 11 47 47](https://cloud.githubusercontent.com/assets/1408922/18469298/f68a688a-79a7-11e6-9599-a8d2a4a14c0a.png)

**Comment by carlobaldassi** [comment]
Same as #76, already fixed on latest version.
