### ISSUE TITLE
Syntax Error: Auto-adding space before parens

### ISSUE THREAD

**Issue by bitmage** [JuliaLang/julia-vim#80]
If I type:

```julia
foo()
```

julia-vim automatically adds a space before the parens, resulting in:

```julia
foo ()
```

Which is invalid syntax.  Is anyone else getting this behavior?  Could it be due to an interaction with some other plugin I have?  This is my current list of installed plugins:

```txt
L9
ack.vim
ctrlp
elm.vim
julia-vim
nerdcommenter
rust.vim
syntastic
vim-clojure-static
vim-coffee-script
vim-conque
vim-cucumber
vim-elixir
vim-fireplace
vim-fugitive
vim-go
vim-json
vim-matchit
vim-ragtag
vim-rails
vim-sexp
vim-surround
vim-textobj-rubyblock
vim-textobj-user
```

**Comment by mbaz** [comment]
I don't experience this behavior.

**Comment by carlobaldassi** [comment]
This was reported in #67 and it's apparently due to the `vim-sexp` plugin.
It would be nice to identify and solve this problem in the interaction between the two plugins.

**Comment by bitmage** [comment]
Confirmed.  Removing `vim-sexp` resolves the issue.  Maybe there's another lisp out there with the extension '.jl'.  The pairing of parens and quotes was nice.  But oh well.
